- name: add ssh key for dan
  authorized_key:
    user: dan
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFr1W9y4QUKxwboCMw1vNnazJzA+PfhXhGGL2+v5MJlu vagrant@ubuntu2204.localdomain

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file}}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
