---

- hosts: all
  become: true
  tasks: 
  
  - name: Update dnf cache of CentOS Dist.
    dnf:
      update_cache=true
    when: ansible_distribution == "CentOS"

  - name: Install latest httpd and php package in CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

#  - name: Enable and start httpd and php package in CentOS
#    systemd:
#      name: 
#        - httpd
#        - php
#      state: restarted
#      enabled: true
#    when: ansible_distribution == "CentOS"
  
##################################################################


  - name: Update dnf cache of Ubuntu Dist.
    apt:
      update_cache=true
    when: ansible_distribution == "Ubuntu"


  - name: Install latest apache2 and php package in Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


#  - name: Enable and start apache2 and php package in Ubuntu
#    systemd:
#      name: 
#        - apache2
#        - libapache2-mod-php
#      state: restarted
#      enabled: true
#    when: ansible_distribution == "Ubuntu"

