---

- hosts: all
  become: true
  tasks: 
  

  - name: Install latest httpd and php package in CentOS
    package:
      name: 
        - '{{ apache_package }}'
        - '{{ php_package }}'
      state: latest
      update_cache: true
