---

- hosts: all
  become: true
  tasks: 
  
  - name: Remove httpd and php packages
    yum:
      name: 
        - httpd
        - php
      state: absent
    when: ansible_distribution in ["CentOS"]


  - name: Remove apache2 and php  packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Ubuntu"]

