---

- hosts: all
  become: true
  tasks: 
  
  - name: Remove httpd package
    yum:
      name: httpd
      state: absent
    when: ansible_distribution in ["CentOS"]

  - name: Remove ssl module
    yum:
      name: php 
      state: absent
    when: ansible_distribution in ["CentOS"]



  - name: Remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution in ["Ubuntu"]

  - name: Remove ssl module
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Ubuntu"]

