---

- hosts: all
  become: true
  tasks:

    - name: update repository index (CentOS)
      tags: always
      dnf:
        update_cache: true
      when: ansible_distribution == "CentOS"
  
    - name: update repository index (Ubuntu)
      tags: always
      apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base
   
- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web-servers
  become: true
  roles:
    - web-servers

- hosts: db-servers
  become: true
  roles:
    - db-servers

- hosts: file-servers
  become: true
  roles:
    - file-servers
