---

- hosts: all
  become: true
  pre_tasks: 
  
  - name: install updates (CentOS)
    tags: always
    dnf: 
      update_only: true
      update_cache: true
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always    
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"  


- hosts: web-servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: web-servers, apache, php, Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: install apache and php for CentOS servers
    tags: apache, php, CentOS, web-servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db-servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: mariadb, mariadb-server, Ubuntu, db-servers
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package (CentOS)
    tags: mariadb, mariadb-server, CentOS, db-servers
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: file-servers
  become: true
  tasks:

  - name: install samba package
    tags: samba, file-servers
    package:
      name: samba
      state: latest
